BookingHotelUI/Models/ViewModels/HomeViewModel.cs
using Application.Services.UserHotelServices.SearchHotelsByNameAndDate;
using Application.Services.UserHotelServices.ShowPopularHotels;

namespace BookingHotelUI.Models.ViewModels
{
    public class HomeViewModel
    {
        public List<IGrouping<bool, SearchHotelsByNameAndDateDto>>? SearchHotel { get; set; } 

        public List<PopularHotelDto>? PopularHotels { get; set; }

        public SearchViewModel? Search { get; }
    }
}

BookingHotelUI/Models/ViewModels/SearchViewModel.cs
namespace BookingHotelUI.Models.ViewModels
{
    public class SearchViewModel
    {
        public string City { get; set; } = null!;

        public DateTime? StartDate { get; set; }

        public DateTime? EndDate { get; set; }
    }
}

BookingHotelUI/Areas/Customer/Controllers/HomeController.cs
using Application.Services.UserHotelServices.UserFacadeHotelService;
using BookingHotelUI.Areas.Customer.Models;
using Domain.Entites;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BookingHotelUI.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly IUserHotelService userHotelService;
        private readonly UserManager<User> userManager;

        public HomeController(IUserHotelService userHotelService, UserManager<User> userManager)
        {
            this.userHotelService = userHotelService;
            this.userManager = userManager;
        }
        

        public async Task<IActionResult> Index()
        {
            var userId = userManager.GetUserId(User);
            var model = new CustomerViewModel
            {
                BookingData = await userHotelService.GetUserData.GetBookingData(userId),
                UserData = await userHotelService.GetUserData.ExecuteAsync(userId)
            };

            return View(model);
        }
    }
}

BookingHotelUI/Controllers/HomeController.cs
using Application.Services.CommentServices.AddComment;
using Application.Services.CommentServices.CommentFacadeService;
using Application.Services.UserHotelServices.SearchHotelsByNameAndDate;
using Application.Services.UserHotelServices.UserFacadeHotelService;
using BookingHotelUI.Models;
using BookingHotelUI.Models.ViewModels;
using Domain.Entites;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookingHotelUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserHotelService userHotelService;
        private readonly UserManager<User> userManager;
        private readonly ICommentService commentService;

        public HomeController(ILogger<HomeController> logger,
            IUserHotelService userHotelService, 
            UserManager<User> userManager,
            ICommentService commentService)
        {
            _logger = logger;
            this.userHotelService = userHotelService;
            this.userManager = userManager;
            this.commentService = commentService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new HomeViewModel
            {
                PopularHotels = await userHotelService.PopularHotels.ExecuteAsync()
            };


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SearchForm(int cityId, DateTime startDate, DateTime endDate)
        {


            var model = await userHotelService.SearchHotel.ExecuteAsync(cityId, startDate, endDate);


            TempData["startDate"] = startDate;
            TempData["endDate"] = endDate;

           
            return View(model);
           
        }

        
        public async Task<JsonResult> GetHotels(string? search)
        {
            var hotels = await userHotelService.GetHotels.ExecuteAsync(search);
            var model = new JsonResult(hotels);
            ;
            return model;
        }

        public async Task<StatusCodeResult> AddComment(AddCommentDto comment)
        {
            var userId = userManager.GetUserId(User);
            comment.UserId = userId;
            var userData = await userHotelService.GetUserData.ExecuteAsync(userId);
            comment.UserName = userData.FullName;
            var result = await commentService.AddComment.ExecuteAsync(comment);
            if (result)
            {
                return StatusCode(200);

            }
            else
            {
                return StatusCode(400);

            }
        }

        public async Task<IActionResult> Track(int? bookingId)
        {
            var model = await userHotelService.TrackOrder.TrackOrderAsync(bookingId);
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookingHotelUI/Controllers/ShoppingController.cs
using Application.Services.PaymentServices.PaymentFacadeService;
using Application.Services.UserHotelServices.OrderForBookingHotel;
using Application.Services.UserHotelServices.UserFacadeHotelService;
using BookingHotelUI.Models.ViewModels;
using Domain.Entites;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookingHotelUI.Controllers
{
    public class ShoppingController : Controller
    {
        private readonly IUserHotelService userHotelService;
        private readonly UserManager<User> userManager;
        private readonly IPaymentService paymentService;

        public ShoppingController(IUserHotelService userHotelService, UserManager<User> userManager
            ,IPaymentService paymentService)
        {
            this.userHotelService = userHotelService;
            this.userManager = userManager;
            this.paymentService = paymentService;
        }
        public async Task<IActionResult> ShowHotel(int hotelId, DateTime startDate, DateTime endDate)
        {
            var model = await userHotelService.ShowRelatedHotel.ExecuteAsync(hotelId, startDate, endDate);
            return View(model);
        }

        public async Task<IActionResult> RegisterBooking(BookingViewModel model)
        {
            var lengthOfStay = (int) (model.EndDate - model.StartDate).TotalDays;
           
            var ss = new BookingViewModel
            {
                EndDate = model.EndDate,
                HotelId = model.HotelId,
                RoomId = model.RoomId,
                LengthOfStay = lengthOfStay,
                Price = model.Price,
                StartDate = model.StartDate,
                Image = model.Image,
                HotelName = model.HotelName,
                RoomName = model.RoomName
            };

            TempData["BookingViewMode"] = JsonConvert.SerializeObject(ss);



            if (User.Identity.IsAuthenticated)
            {
                var user = await userManager.GetUserAsync(User);
                var infoUser = new BookingRegisterViewModel
                {
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    NationalCode = user.NationalCode,
                    PhoneNumber = user.PhoneNumber
                };

                return View(infoUser);
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterBooking(BookingRegisterViewModel register)
        {
            var userFind = await userManager.FindByNameAsync(register.NationalCode);

            if(userFind is null)
            {
                //return RedirectToAction("Register", "Account", new
                //{
                //    FirstName = register.FirstName,
                //    LastName = register.LastName,
                //    NationalCode = register.NationalCode,
                //    PhoneNumber = register.PhoneNumber,
                //    Email = register.Email
                //});

                var newUser = new User
                {
                    FirstName = register.FirstName,
                    LastName = register.LastName,
                    Email = register.Email,
                    PhoneNumber = register.PhoneNumber,
                    UserName = register.NationalCode,
                    NationalCode = register.NationalCode,
                };

                var result = await userManager.CreateAsync(newUser, register.PhoneNumber);
            }

            var ss = new BookingRegisterViewModel
            {
                FirstName = register.FirstName,
                LastName = register.LastName,
                NationalCode = register.NationalCode,
                PhoneNumber = register.PhoneNumber,
                Email = register.Email,
                PassengerName = register.PassengerName,
                PassengerFamilyName = register.PassengerFamilyName
            };

            TempData["RegisterInfo"] = JsonConvert.SerializeObject(ss);

            return RedirectToAction("ConfirmDataBooking");
        }

        public async Task<IActionResult> ConfirmDataBooking()
        {
            return View();
        }
        //ShippingPayment
        public async Task<IActionResult> PayAction(OrderDto data)
        {
            
            var user = await userManager.FindByEmailAsync(data.UserEmail);
            data.UserId = user.Id;

            var bookingId = await userHotelService.OrderForBooking.ExecuteAsync(data);
            TempData["RoomIdForRoomBooking"] = data.RoomId;
            // register payment
            var payment = await paymentService.PayForBooking(bookingId);

            // send to payment gate
            return RedirectToAction("Index", "Pay", new { PaymentId = payment.PaymentId, UserIdd = user.Id });
            return View();
        }

        public async Task<IActionResult> CheckOut(string? userId)
        {
            if(userId is not null)
            {
                var model = await userHotelService.GetUserData.ShowResultAfterPay(userId);
                return View(model);
            }

            return View();
            
        }
    }
}

BookingHotelUI/Views/Home/Index.cshtml
@model HomeViewModel;

@{
    ViewData["Title"] = "Home Page";

    string GetColorRate(double rate){
        if(rate >= 7){
            return "success";
        }else if( rate < 7 && rate >= 5){
            return "warning";
        }else{
            return "danger";
        }
    }
}

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#trackOrderModal">
    Track Order
</button>

<!-- Modal -->
<div class="modal fade" id="trackOrderModal" tabindex="-1" aria-labelledby="trackOrderModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="trackOrderModalLabel">Track Order</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form asp-action="Track" method="get">
                    <label class="form-label" >Booking Id</label>
                    <input class="form-control" name="bookingId" type="number" />

                    <input type="submit" value="Search" class="btn btn-success" />
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                
            </div>
        </div>
    </div>
</div>


<section class="my-3 p-4 border rounded">
    <form asp-action="SearchForm" method="post" >
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row  ">
            <h3>Searh Hotels</h3>
            <hr />
            <label class="form-label" asp-for="Search.City"></label>
            <select class="form-select" id="city" name="cityId" placeholder="city,hotel name..." type="text"></select>
            
            <div class="col-sm-6">
                <label class="form-label" asp-for="Search.StartDate"></label>
                <input class="form-control" asp-for="Search.StartDate" id="startDate" type="date" />
            </div>
            <div class="col-sm-6">
                <label class="form-label" asp-for="Search.EndDate"></label>
                <input class="form-control" asp-for="Search.EndDate" id="endDate" type="date" />
            </div>
            
        </div>
        
        <input type="submit" value="Search In Hotels" class="form-control btn btn-info mt-4" />
        
    </form>
    <div class="row mt-3 text-center">
        <h6 id="showDate"></h6>
    </div>
</section>





<div class="swiper mySwiper ">
    <div class="swiper-wrapper">
        @foreach (var item in Model.PopularHotels)
        {
            <div class="swiper-slide" >

                <div class="card">
                    <img class="card-img-top" src="@item.Image">

                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-subtitle text-muted">@item.City</p>
                        
                        <p>
                            @for (var i = 0; i < item.NumberOfStar; i++)
                            {
                                <i class="fa-solid fa-star text-warning"></i>
                            }
                        </p>

                        <h5 class="btn btn-@GetColorRate(item.Rate)">@item.Rate</h5>


                    </div>
                </div>

            </div>
        }
        
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
</div>

@section Scripts{
    
    <script src="~/lib/select2/js/select2.full.min.js"></script>

    <script>
        var swiper = new Swiper(".mySwiper", {
            slidesPerView: 3,
            spaceBetween: 30,
            slidesPerGroup: 3,
            loop: true,
            loopFillGroupWithBlank: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
        });
    </script>


    <script>
        var startDate = document.getElementById("startDate");
        var endDate = document.getElementById("endDate");
        var showDate = document.getElementById("showDate");
        var search = document.getElementById("city");
        

        $("#city").select2({
            theme: "bootstrap4",
            placeholder: 'City or Hotel...',
            ajax:{
                url : `Home/GetHotels`,
                data : (params) => {
                     var query = {
                         search : params.term
                     }
                     return query;
                      
                },// end data
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.text,
                                id: item.id
                            }
                        })
                    };
                },// processResults
            }
        });
        
        

        startDate.addEventListener("click", (e) => {
            var date = new Date();
            let nowDate = date.toISOString().split('T')[0]
            startDate.setAttribute("min", nowDate)
            console.log(date)
        })

        

        startDate.addEventListener("change",(e) => {

            var date = new Date(startDate.value);
            date.setDate(date.getDate() + 1);
            let nextDay = date.toISOString().split('T')[0]
            
            endDate.setAttribute("min", nextDay);
            endDate.value = "";

            
        })

        endDate.addEventListener("change",(e) => {
            var start = new Date(startDate.value)
            var end = new Date(endDate.value)
            var diff = end.getDate() - start.getDate() 
            
            console.log(search.value);
            console.log($("#city").select2('data')[0].text);
            console.log($("#city").select2('data')[0].id);

            showDate.innerHTML = diff + " Night"
        });


        
    </script>
}

BookingHotelUI/Views/Home/SearchForm.cshtml
@using Application.Services.UserHotelServices.SearchHotelsByNameAndDate
@model List<IGrouping<bool, SearchHotelsByNameAndDateDto>>;

@{
    var startDate = TempData["startDate"];
    var endDate = TempData["endDate"];
}
<h1>Hotels</h1>

@foreach (var hotels in Model)
{
    
    
    @foreach (var hotel in hotels)
    {
        <div class="row border rounded p-3 my-3">
            <div class="col-3">
                <img class="img-fluid" src="@hotel.Image">
            </div>

            <div class="col-6 ">
                <h2> @hotel.Name</h2>
                
                <p> @for (var i = 0; i < hotel.Star; i++)
                    {
                        <i class="text-warning fa-solid fa-star"></i>
                    }
                </p>
                <h6>@hotel.Address</h6>

                @if(hotels.Key == true){
                    <h6 class="bg-success border d-inline-block rounded-circle p-2">Free</h6>
                }else{
                    <h6 class="bg-danger border d-inline-block rounded-circle p-2">No Capcity</h6>
                }
            </div>
            <div class="col-3 d-flex flex-column border-start justify-content-center align-content-center">

                <p>Start Price for <strong>1 night</strong> </p>
                
                <h3 class="text-danger fs-4 ">@hotel.StartPrice.ToString("C")</h3>
                
                <a asp-action="ShowHotel" asp-controller="Shopping" asp-route-hotelId="@hotel.Id" asp-route-startDate="@startDate" asp-route-endDate="@endDate"
                    class="justify-content-end btn btn-outline-danger">Room Reserv</a>
                
            </div>
        </div>
    }
}

BookingHotelUI/Views/Home/Track.cshtml
@using Application.Services.UserHotelServices.GetUserData
@model GetBookingDataDto;

@if(Model is null){
    <div class="text-center">
        <h3>Not any thing</h3>
    </div>
}else{
    <div class="row">
        <div class="card">
            <div class="card-header bg-white">
                <h3 class="card-header">Your Information about your booking</h3>
            </div>

            <div class="card-body p-3">

                <!-- first row -->
                <div class="d-flex justify-content-around align-items-baseline mb-3">
                    <div>
                        <h3>Name: </h3>
                        <p>@Model.PassengerName</p>
                    </div>

                    <div>
                        <h3>Family: </h3>
                        <p>@Model.PassengerFamilyName</p>
                    </div>
                </div>


                <!-- second row -->
                <div class="d-flex justify-content-around align-items-baseline mb-3">
                    <div>
                        <h3>Start Date: </h3>
                        <p>@Model.StartDate.ToShortDateString()</p>
                    </div>

                    <div>
                        <h3>End Date: </h3>
                        <p>@Model.EndDate.ToShortDateString()</p>
                    </div>
                </div>

                <!-- third row -->
                <div class="d-flex justify-content-around align-items-baseline mb-3">
                    <div>
                        <h3>BookingId: </h3>
                        <p>@Model.BookingCode</p>
                    </div>

                    <div>
                        <h3>Status: </h3>
                        <p>@Model.BookingStatus</p>
                    </div>
                </div>

                <!-- fouth row-->
                <div class="d-flex justify-content-around align-items-baseline mb-3">
                    <div>
                        <h3>Hotel: </h3>
                        <p>@Model.HotelName</p>
                    </div>

                    <div>
                        <h3>Room: </h3>
                        <p>@Model.RoomName</p>
                    </div>
                </div>

                <!-- fifth row -->
                <div class="d-flex justify-content-around align-items-baseline mb-3">
                    <div>
                        <h3>Length: </h3>
                        <p>@Model.LengthOfStay</p>
                    </div>

                    <div>
                        <h3>Total Price </h3>
                        <p>@Model.TotalPrice.ToString("C")</p>
                    </div>
                </div>

            </div>

            <div class="card-footer bg-white">
                <div>
                    <button class="btn btn-success" onclick="window.print()">Print</button>
                </div>
            </div>
        </div>
    </div>
}